pipeline:
  identifier: Build_sum_service_1691506759790
  name: Build sum-service
  orgIdentifier: default
  projectIdentifier: default_project
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: francesco-plt/sum-service
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  type: Run
                  name: npm_run_build
                  identifier: npm_run_build
                  spec:
                    shell: Sh
                    command: npm run build
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
